name: C CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install sqlite3
      run: sudo apt-get install -y libsqlite3-dev

    - name: Build
      run: make

    - name: Run (smoke test)
      run: echo "Build done"
